### ISSUE TITLE
Deploy latest version to Chrome Store

### ISSUE THREAD

**Issue by samgiles** [triblondon/health-status-formatter#5]
@robertshilston It seems you are the current author so you might need to do it?

**Comment by robertshilston** [comment]
If you can prepare the new crx file, I can upload it.

**Comment by robertshilston** [comment]
I'm also going to change the app so that there's a group of people who can manage this.

**Comment by samgiles** [comment]
I've prepared a 'crx'.  However it also gave me a private key '.pem'.  I've never uploaded to the Chrome Web Store so I don't know if you'll require that or why it's given me one?

**Comment by robertshilston** [comment]
In 30 minutes you should have the ability to upload direct to
https://chrome.google.com/webstore/developer/dashboard/g07532873522869236396.
Can you give it a go?

Thanks.

On 13 January 2015 at 17:47, Samuel Giles <notifications@github.com> wrote:

> I've prepared a 'crx'. However it also gave me a private key '.pem'. I've
> never uploaded to the Chrome Web Store so I don't know if you'll require
> that or why it's given me one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/triblondon/health-status-formatter/issues/5#issuecomment-69786579>
> .
>



-- 
*Robert Shilston PhD*
Director of Engineering
FT Technology

+44 (0)7940 387593
Number One Southwark Bridge, London SE1 9HL


<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by samgiles** [comment]
You might need to transfer the existing app from your account to the group account.

**Comment by samgiles** [comment]
This is done and is managed by the ft-chrome-webstore-apps-internal group.  Thanks for your help.
